name: netcalc
version: '4.1.0'
summary: Simple network calculator
description: |
  A program that converts values from the IP address and prefix of the subnet mask.
  It has the ability to download data from the interface.
  It calculates values for the subnet mask, network address,
  broadcast address, first and last address and number of hosts.
grade: stable
base: core18
license: GPL-2.0

apps:
  netcalc:
    command: netcalc
    plugs:
      - network-bind
      - locale-control
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

parts:
  netcalc:
    plugin: cmake
    source: https://github.com/radlesner/netcalc.git
    build-packages:
      - cmake
      - make
      - pkg-config
      - libgtk-3-dev
      - libpango1.0-dev
      - libfontconfig1-dev
    stage-packages:
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf2.0-0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - hicolor-icon-theme
      - fonts-dejavu-core
